### ISSUE TITLE
Q: How in the WORLD do I choose one StaticGen?

### ISSUE THREAD

**Issue by geraldb** [jondaiello/jondaiello-com#1]
A: Pick the No. 1 ;-) Jekyll works great. Good luck. Cheers.

**Comment by jondaiello** [comment]
Thanks @geraldb! I'm still a little skeptical, as Jekyll runs on ruby, and I'd like this to be cross-platform compatible.

**Comment by geraldb** [comment]
@jondaiello  Ruby runs anywhere (Windows, Linux, Mac, etc.) It is cross-platform.  FYI: Only older Jekyll versions (before 3) had trouble with windows. I have been running Jekyll on Windows for years. Anyways always great to study alternatives. See the [Stay Static collection](http://staystatic.github.io) as an example. Cheers.

**Comment by jondaiello** [comment]
@geraldb Thanks for setting me straight! It's all new to me so this is definitely helpful.
